site_name: aify
site_url: https://aify.run
repo_url: https://github.com/shellc/aify
edit_uri: blob/main/docs/
site_author: shellc

theme:
  name: readthedocs
  include_homepage_in_sidebar: false
  navigation_depth: 2
  analytics:
    gtag: G-3QEZ4BHZYC

nav:
  - getting_started.md
  - dive_into_apps.md
  - app_template.md
  - enhance_with_python.md
  - rest_api.md
  - Examples:
    - examples/llm_generation.md
    - examples/chatbot.md
