# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=python
runtime: python311 # or another supported version

instance_class: F2

entrypoint: python -m aify run --port $PORT

handlers:
- url: /apps/static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
